site_name: farmabi - Business Intelligence
site_description: Documentacion del proyecto BI farmabi
docs_dir: docs

nav:
  - Inicio: index.md
  - Guía de Proyecto Sello:
      - Guía del proyecto: proyecto-sello/index.md
  - Silabos:
      - Silabo 2026-1: silabo_bi_2026_1.md
      - Silabo 2026-2: silabo_bi_2026_2.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js
